apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: hello
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/wonjoyoo/hello
      ref:
        branch: main
